### ISSUE TITLE
samples/smp_shared does not build: K_THREAD_DEFINE and -retainCount fail the Clang AST dump

### ISSUE THREAD

**Issue by rodrigopex** [rodrigopex/objective-z#434]
## Context

`just test-smp` (`qemu_cortex_a53/smp`) is the only recipe that exercises two cores, and
it is **not in CI** — so nothing catches a regression in it. `samples/smp_shared` has not
been buildable for some time: three independent failures, of which #428 fixes one.

Found while landing #428, and proven rather than inferred: with the unmodified `main.m`
restored and #428's rejection temporarily disabled and rebuilt, the failure reproduces
identically. So none of this is caused by #428.

## Observed

`oz_static_ast_check.sh` fails the build on four diagnostics from the Clang AST dump:

```
main.m:236:36: error: expected identifier                /* K_THREAD_DEFINE */
main.m:236:1:  error: type specifier missing, defaults to 'int'
main.m:245:53: error: no visible @interface for 'Counter' declares the selector 'retainCount'
main.m:266:42: error: (same)
```

Two distinct causes:

1. **`K_THREAD_DEFINE` at file scope does not parse in the AST dump.** The macro is not
   visible to the dump's include set — which is the same reason the file already declares
   `printk` by hand.
2. **`[shared_counter retainCount]`.** `emit::render_message` intercepts `retainCount`
   ahead of dispatch resolution and lowers it to `oz_static_retain_count`, so no
   `@interface` declares the selector and Clang refuses the send. Declaring it on
   `Counter` is not a fix — it would generate a prototype with no definition. Related to
   the separate `INTRINSIC_SELECTORS` issue.

The third cause, fixed in #428: `Counter` declared `- (int)count` while `OZArray` — pulled
in by the Foundation umbrella this file imports — declares `- (size_t)count`, so
`generics::check_dispatch_signature_agreement` refused the shared
`OZ_PROTOCOL_SEND_count` and stopped configure at the first step. Renamed to `-total`.

#428 takes this sample's dump error count from **6 to 4**, measured with the same clang
flags on both sources.

## Expected

`just test-smp` reaches **10 of 10**. Either give the AST dump declarations it can see —
a Zephyr stub for `K_THREAD_DEFINE`, the way `tests/behavior/include/zephyr_stubs` serves
the host corpus — or switch the sample to spellings that survive the dump.

Worth deciding at the same time whether `just test-smp` belongs in CI. A recipe that is
the sole cover for two-core behaviour, and that nothing runs automatically, will break
again — this issue is the evidence.

## Workaround

None. The sample does not build.

## Metadata

| Field | Value |
|-------|-------|
| Filed by | MAINTAINER |
| Blocking | NO |
| Found while landing | #428 |
